// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGrpcRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGrpcRequest) Reset()         { *m = GetGrpcRequest{} }
func (m *GetGrpcRequest) String() string { return proto.CompactTextString(m) }
func (*GetGrpcRequest) ProtoMessage()    {}
func (*GetGrpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *GetGrpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGrpcRequest.Unmarshal(m, b)
}
func (m *GetGrpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGrpcRequest.Marshal(b, m, deterministic)
}
func (m *GetGrpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGrpcRequest.Merge(m, src)
}
func (m *GetGrpcRequest) XXX_Size() int {
	return xxx_messageInfo_GetGrpcRequest.Size(m)
}
func (m *GetGrpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGrpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGrpcRequest proto.InternalMessageInfo

func (m *GetGrpcRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetGrpcResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGrpcResponse) Reset()         { *m = GetGrpcResponse{} }
func (m *GetGrpcResponse) String() string { return proto.CompactTextString(m) }
func (*GetGrpcResponse) ProtoMessage()    {}
func (*GetGrpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *GetGrpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGrpcResponse.Unmarshal(m, b)
}
func (m *GetGrpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGrpcResponse.Marshal(b, m, deterministic)
}
func (m *GetGrpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGrpcResponse.Merge(m, src)
}
func (m *GetGrpcResponse) XXX_Size() int {
	return xxx_messageInfo_GetGrpcResponse.Size(m)
}
func (m *GetGrpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGrpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGrpcResponse proto.InternalMessageInfo

func (m *GetGrpcResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetGrpcRequest)(nil), "proto.GetGrpcRequest")
	proto.RegisterType((*GetGrpcResponse)(nil), "proto.GetGrpcResponse")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x52, 0xe1, 0xe2, 0x73,
	0x4f, 0x2d, 0x71, 0x2f, 0x2a, 0x48, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xb4,
	0xb9, 0xf8, 0xe1, 0xaa, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x61, 0x2a, 0x61, 0x5c, 0x23, 0x47, 0x2e, 0x6e, 0x90, 0xca, 0xe0, 0xd4,
	0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x23, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x61, 0xbd, 0xc4,
	0x82, 0x4c, 0x3d, 0x54, 0xbb, 0xa4, 0x44, 0x50, 0x05, 0x21, 0x46, 0x2b, 0x31, 0x24, 0xb1, 0x81,
	0x5d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xae, 0xde, 0xd8, 0xb5, 0xaf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcServiceClient interface {
	Get(ctx context.Context, in *GetGrpcRequest, opts ...grpc.CallOption) (*GetGrpcResponse, error)
}

type grpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServiceClient(cc *grpc.ClientConn) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) Get(ctx context.Context, in *GetGrpcRequest, opts ...grpc.CallOption) (*GetGrpcResponse, error) {
	out := new(GetGrpcResponse)
	err := c.cc.Invoke(ctx, "/proto.GrpcService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServiceServer is the server API for GrpcService service.
type GrpcServiceServer interface {
	Get(context.Context, *GetGrpcRequest) (*GetGrpcResponse, error)
}

// UnimplementedGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcServiceServer struct {
}

func (*UnimplementedGrpcServiceServer) Get(ctx context.Context, req *GetGrpcRequest) (*GetGrpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGrpcServiceServer(s *grpc.Server, srv GrpcServiceServer) {
	s.RegisterService(&_GrpcService_serviceDesc, srv)
}

func _GrpcService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).Get(ctx, req.(*GetGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GrpcService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
